config/routes.rb
Rails.application.routes.draw do
    namespace :api do
      namespace :v1 do
        resources :searches do
          get :cargos, on: :collection
          get :positions, on: :collection
        end
      end
    end

    resources :vessels, except: :show do
      resources :positions, except: :show
    end

    resources :cargos, except: :show
    resources :ports, except: :show
    root 'welcome#index'
    get 'welcome/index'

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  belongs_to :port
  validates :title, :port_id, :open_date, :capacity, presence: true
  default_scope -> { order(open_date: :asc) }
end

app/models/port.rb
class Port < ActiveRecord::Base
  has_many :positions, dependent: :destroy
  has_many :cargos, dependent: :destroy
  validates :title, :lat, :lng, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :vessel
  belongs_to :port
  validates :vessel_id, :port_id, :open_date, presence: true
  default_scope -> { order(open_date: :asc) }
end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  has_many :positions, dependent: :destroy
  validates :title, :hold_capacity, presence: true
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json
end

app/controllers/api/v1/searches_controller.rb
class Api::V1::SearchesController < Api::V1::BaseController
  DELTA_PERCENT = 10

  def cargos
    respond_with find_cargos
  end

  def positions
    respond_with find_positions 
  end

  private

  def find_cargos
    @position = Position.find(params[:position_id])
    @hold_capacity = @position.vessel.hold_capacity
    limit = @hold_capacity * (1.0 + DELTA_PERCENT / 100)
    @cargos = Cargo.where(port: @position.port, open_date: @position.open_date)
      .where("capacity <= ?", limit)
  end

  def find_positions
    @cargo = Cargo.find(params[:cargo_id])
    limit = @cargo.capacity * (1.0 - DELTA_PERCENT / 100)
    @positions = Position.joins(:vessel).where(port: @cargo.port, open_date: @cargo.open_date)
     .where("vessels.hold_capacity >= ?", limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:edit, :update, :destroy]

  def index
    @cargos = Cargo.all
  end

  def new
    @cargo = Cargo.new
  end

  def edit
  end

  def create
    @cargo = Cargo.new(cargo_params)
    if @cargo.save
      redirect_to cargos_url, notice: 'Cargo was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cargo.update(cargo_params)
      redirect_to cargos_url, notice: 'Cargo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cargo.destroy
    redirect_to cargos_url, notice: 'Cargo was successfully destroyed.'
  end

  private

  def set_cargo
    @cargo = Cargo.find(params[:id])
  end

  def cargo_params
    params.require(:cargo).permit(:title, :port_id, :open_date, :capacity)
  end
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:edit, :update, :destroy]

  def index
    @ports = Port.all
  end

  def new
    @port = Port.new
  end

  def edit
  end

  def create
    @port = Port.new(port_params)
    if @port.save
      redirect_to ports_url, notice: 'Port was successfully created.'
    else
      render :new
    end
  end

  def update
    if @port.update(port_params)
      redirect_to ports_url, notice: 'Port was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @port.destroy
    redirect_to ports_url, notice: 'Port was successfully destroyed.'
  end

  private

  def set_port
    @port = Port.find(params[:id])
  end

  def port_params
    params.require(:port).permit(:title, :lat, :lng)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:edit, :update, :destroy]
  before_action :set_vessel, only: [:index, :new, :create]

  def index
    @positions = @vessel.positions.order(open_date: :desc)
  end

  def new
    @position = @vessel.positions.build
  end

  def edit
  end

  def create
    @position = @vessel.positions.build(position_params)
    if @position.save
      redirect_to vessel_positions_path(@position.vessel), notice: 'Position was successfully created.'
    else
      render :new
    end
  end

  def update
    if @position.update(position_params)
      redirect_to vessel_positions_path(@position.vessel), notice: 'Position was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @position.destroy
    redirect_to vessel_positions_path(@position.vessel), notice: 'Position was successfully destroyed.'
  end

  private

  def set_vessel
    @vessel = Vessel.find(params[:vessel_id])
  end

  def set_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:port_id, :open_date)
  end
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:edit, :update, :destroy]

  def index
    @vessels = Vessel.all
  end

  def new
    @vessel = Vessel.new
  end

  def edit
  end

  def create
    @vessel = Vessel.new(vessel_params)
    if @vessel.save
      redirect_to vessels_url, notice: 'Vessel was successfully created.'
    else
      render :new
    end
  end

  def update
    if @vessel.update(vessel_params)
      redirect_to vessels_url, notice: 'Vessel was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @vessel.destroy
    redirect_to vessels_url, notice: 'Vessel was successfully destroyed.'
  end

  private

  def set_vessel
    @vessel = Vessel.find(params[:id])
  end

  def vessel_params
    params.require(:vessel).permit(:title, :hold_capacity)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cargos/_form.html.slim
= form_for @cargo do |f|
  = render 'common/errors', resource: @cargo
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :port
    = f.collection_select :port_id, Port.all, :id, :title, { prompt: 'Select port'}
  .field
    = f.label :open_date
    = f.date_select :open_date
  .field
    = f.label :capacity
    = f.number_field :capacity
  .actions = f.submit

app/views/cargos/edit.html.slim
h1 Editing cargo
== render 'form'
= link_to 'Back', cargos_path

app/views/cargos/index.html.slim
h1 Listing cargos
p = link_to "Home", root_path

table
  thead
    tr
      th ID
      th Title
      th Port
      th Open date
      th Capacity
      th
      th
  tbody
    - @cargos.each do |cargo|
      tr
        td = cargo.id
        td = cargo.title
        td = cargo.port.title
        td = cargo.open_date
        td = cargo.capacity
        td = link_to 'Edit', edit_cargo_path(cargo)
        td = link_to 'Destroy', cargo, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Cargo', new_cargo_path

app/views/cargos/new.html.slim
h1 New cargo
== render 'form'
= link_to 'Back', cargos_path

app/views/common/_errors.slim
- if resource.errors.any?
  .hide
    #error_explanation
      p = "#{pluralize(resource.errors.count, "error")}:"
      ul
        - resource.errors.full_messages.each do |message|
          li = message

app/views/common/_notice.slim
p#notice = notice

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Seatruck
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'common/notice'
    = yield

app/views/ports/_form.html.slim
= form_for @port do |f|
  = render 'common/errors', resource: @port
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lng
    = f.text_field :lng
  .actions = f.submit

app/views/ports/edit.html.slim
h1 Editing port
= render 'form'
= link_to 'Back', ports_path

app/views/ports/index.html.slim
h1 Listing ports
p = link_to "Home", root_path

table
  thead
    tr
      th Title
      th Lat
      th Lng
      th
      th

  tbody
    - @ports.each do |port|
      tr
        td = port.title
        td = port.lat
        td = port.lng
        td = link_to 'Edit', edit_port_path(port)
        td = link_to 'Destroy', port, data: { confirm: 'Are you sure?' }, method: :delete

br
= link_to 'New Port', new_port_path

app/views/ports/new.html.slim
h1 New port
= render 'form'
= link_to 'Back', ports_path

app/views/positions/_form.html.slim
= form_for([position.vessel, position]) do |f|
  = render 'common/errors', resource: position
  .field
    = f.label :port
    = f.collection_select :port_id, Port.all, :id, :title, { prompt: 'Select port'}
  .field
    = f.label :open_date
    = f.date_select :open_date
  .actions = f.submit

app/views/positions/edit.html.slim
h1 Editing Position
= render 'form', position: @position
= link_to 'Back', vessel_positions_path

app/views/positions/index.html.slim
h1 Listing Position
h2= @vessel.title

p = link_to "Back to Vessels", vessels_path

table
  thead
    tr
      th ID
      th Port
      th Open date
      th
      th

  tbody
    - @positions.each do |position|
      tr
        td = position.id
        td = position.port.title
        td = position.open_date
        td = link_to 'Edit', edit_vessel_position_path(position.vessel,position)
        td = link_to 'Destroy', vessel_position_path(position.vessel,position), 
            data: { confirm: 'Are you sure?' }, method: :delete

br
= link_to 'New Position', new_vessel_position_path

app/views/positions/new.html.slim
h1 New Position
== render 'form', position: @position
= link_to 'Back', vessel_positions_path

app/views/vessels/_form.html.slim
= form_for @vessel do |f|
  = render 'common/errors', resource: @vessel
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :hold_capacity
    = f.number_field :hold_capacity
  .actions = f.submit

app/views/vessels/edit.html.slim
h1 Editing vessel
== render 'form'
= link_to 'Back', vessels_path

app/views/vessels/index.html.slim
h1 Listing vessels
p = link_to "Home", root_path

table
  thead
    tr
      th ID
      th Title
      th Hold capacity
      th
      th
      th
  tbody
    - @vessels.each do |vessel|
      tr
        td = vessel.id
        td = vessel.title
        td = vessel.hold_capacity
        td = link_to 'Edit', edit_vessel_path(vessel)
        td = link_to 'Positions',  vessel_positions_path(vessel)        
        td = link_to 'Destroy', vessel, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Vessel', new_vessel_path

app/views/vessels/new.html.slim
h1 New vessel
== render 'form'
= link_to 'Back', vessels_path

app/views/welcome/index.html.slim
h1 Welcome to SeaTruck application
p = link_to "Ports", ports_path
p = link_to "Cargos", cargos_path
p = link_to "Vessels", vessels_path
hr

h2 API Requests for search Cargo:
p
  a target="_new" href="/api/v1/searches/cargos.json?position_id=1" Requests 1
p  
  a target="_new" href="/api/v1/searches/cargos.json?position_id=4" Requests 2
  
h2 API Requests for search Position:

p
  a target="_new" href="/api/v1/searches/positions.json?cargo_id=1" Requests 1
p  
  a target="_new" href="/api/v1/searches/positions.json?cargo_id=3" Requests 2